2021-04-30 09:58:57,395 : INFO : Start of Training...
2021-04-30 09:58:57,395 : INFO : Run_id: 2021-04-30_095857_9050266790
2021-04-30 09:58:57,395 : INFO : Start of Data Load, validation and transformation
2021-04-30 09:58:57,395 : INFO : Start of Archiving Old Rejected Files...
2021-04-30 09:58:57,396 : INFO : End of Archiving Old Rejected Files...
2021-04-30 09:58:57,396 : INFO : Start of Archiving Old Validated Files...
2021-04-30 09:58:57,398 : INFO : End of Archiving Old Validated Files...
2021-04-30 09:58:57,398 : INFO : Start of Archiving Old Processed Files...
2021-04-30 09:58:57,398 : INFO : End of Archiving Old Processed Files...
2021-04-30 09:58:57,398 : INFO : Start of Archiving Old Result Files...
2021-04-30 09:58:57,399 : INFO : End of Archiving Old Result Files...
2021-04-30 09:58:57,399 : INFO : Start of Reading values From Schema...
2021-04-30 09:58:57,399 : INFO : End of Reading values From Schema...
2021-04-30 09:58:57,400 : INFO : Start of Validating Column Length...
2021-04-30 09:58:57,400 : INFO : End of Validating Column Length...
2021-04-30 09:58:57,400 : INFO : Start of Validating Missing Values...
2021-04-30 09:58:57,401 : INFO : End of Validating Missing Values...
2021-04-30 09:58:57,401 : INFO : Start of Replacing Missing Values with NULL...
2021-04-30 09:58:57,402 : INFO : End of Replacing Missing Values with NULL...
2021-04-30 09:58:57,402 : INFO : Start of Creating Table...
2021-04-30 09:58:57,403 : INFO : Opened training database successfully
2021-04-30 09:58:57,404 : INFO : Tables created successfully
2021-04-30 09:58:57,404 : INFO : Closed training database successfully
2021-04-30 09:58:57,404 : INFO : End of Creating Table...
2021-04-30 09:58:57,405 : INFO : Opened training database successfully
2021-04-30 09:58:57,405 : INFO : Start of Inserting Data into Table...
2021-04-30 09:58:57,405 : INFO : End of Inserting Data into Table...
2021-04-30 09:58:57,405 : INFO : Start of Exporting Data into CSV...
2021-04-30 09:58:57,405 : INFO : Opened training database successfully
2021-04-30 09:58:57,407 : INFO : End of Exporting Data into CSV...
2021-04-30 09:58:57,408 : INFO : Start of Moving Processed Files...
2021-04-30 09:58:57,408 : INFO : End of Moving Processed Files...
2021-04-30 09:58:57,408 : INFO : End of Data Load, validation and transformation
2021-04-30 09:58:57,408 : INFO : Start of Preprocessing...
2021-04-30 09:58:57,408 : INFO : Start of reading dataset...
2021-04-30 09:58:57,416 : INFO : End of reading dataset...
2021-04-30 09:58:57,416 : INFO : Start of Droping Columns...
2021-04-30 09:58:57,419 : INFO : End of Droping Columns...
2021-04-30 09:58:57,420 : INFO : Start of feature encoding...
2021-04-30 09:58:57,455 : INFO : End of feature encoding...
2021-04-30 09:58:57,456 : INFO : Start of Droping Columns...
2021-04-30 09:58:57,457 : INFO : End of Droping Columns...
2021-04-30 09:58:57,457 : INFO : Start of finding missing values...
2021-04-30 09:58:57,458 : INFO : End of finding missing values...
2021-04-30 09:58:57,458 : INFO : Start of splitting features and label ...
2021-04-30 09:58:57,459 : INFO : End of splitting features and label ...
2021-04-30 09:58:57,459 : INFO : End of Preprocessing...
2021-04-30 09:58:57,460 : INFO : Start of elbow plotting...
2021-04-30 09:58:57,462 : ERROR : Exception raised while elbow plotting:Found array with 0 sample(s) (shape=(0, 7)) while a minimum of 1 is required.
Traceback (most recent call last):
  File "D:\GitHub\Employee-Retention-Prediction\App\apps\tuning\cluster.py", line 27, in elbow_plot
    kmeans.fit(data) # fitting the data to the KMeans Algorithm
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\cluster\_kmeans.py", line 1030, in fit
    X = self._validate_data(X, accept_sparse='csr',
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 650, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 7)) while a minimum of 1 is required.
2021-04-30 09:58:57,465 : ERROR : Unsuccessful, Training model is end with some error
Traceback (most recent call last):
  File "D:\GitHub\Employee-Retention-Prediction\App\apps\tuning\cluster.py", line 27, in elbow_plot
    kmeans.fit(data) # fitting the data to the KMeans Algorithm
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\cluster\_kmeans.py", line 1030, in fit
    X = self._validate_data(X, accept_sparse='csr',
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "D:\Programming\Python\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 650, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 7)) while a minimum of 1 is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\Employee-Retention-Prediction\App\apps\training\train_model.py", line 44, in training_model
    number_of_clusters = self.cluster.elbow_plot(self.X)
  File "D:\GitHub\Employee-Retention-Prediction\App\apps\tuning\cluster.py", line 43, in elbow_plot
    raise Exception()
Exception
